@extends('layout.merchant')
@section('title')
    Dashboard
@endsection
@section('main')
<main class="main">
    <div class="view-header">
      <h1 class="view-title">Overview</h1>
    </div>

    <!-- Metrics Grid -->
    <div class="metrics-grid">
      <div class="stat-card">
        <span class="stat-label">Total Sales (NGN)</span>
        <span class="stat-value">₦ {{$order->sum('total_price')}}.00</span>
        <span class="stat-trend">↑ 12.4% vs last month</span>
      </div>
      <div class="stat-card">
        <span class="stat-label">Total Orders</span>
        <span class="stat-value">{{$order->sum('quantity')}}</span>
        <span class="stat-trend">↑ 4.1% vs last month</span>
      </div>
      <div class="stat-card">
        <span class="stat-label">Checkouts Initiated</span>
        <span class="stat-value">5,892</span>
        <span class="stat-trend" style="color:var(--text-sub)">— Stable</span>
      </div>
    </div>

    <!-- Chart Placeholder -->
    <div class="chart-container">
      <span class="stat-label">Sales Velocity (7 Days)</span>
      <div class="chart-viz" id="bar-chart">
        <!-- Bars generated by script -->
      </div>
    </div>

    <!-- Recent Activity -->
    <div>
      <span class="section-label">Recent Checkouts</span>
      <div class="table-responsive">
        <table class="activity-table">
          <thead>
            <tr>
              <th>Session ID</th>
              <th>Customer</th>
              <th>Amount</th>
              <th>Status</th>
              <th>Time</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td style="font-family:'Space Mono'; color:var(--text-sub)">cs_live_9281...</td>
              <td style="font-weight:700">Taiwo Adekunle</td>
              <td>₦ 12,500.00</td>
              <td><span class="status-pill" style="color:var(--accent); border-color:var(--accent)">Completed</span></td>
              <td style="font-family:'Space Mono'; font-size:11px">2 mins ago</td>
            </tr>
            <tr>
              <td style="font-family:'Space Mono'; color:var(--text-sub)">cs_live_0012...</td>
              <td style="font-weight:700">Chioma Okoro</td>
              <td>₦ 45,000.00</td>
              <td><span class="status-pill" style="color:var(--accent); border-color:var(--accent)">Completed</span></td>
              <td style="font-family:'Space Mono'; font-size:11px">14 mins ago</td>
            </tr>
            <tr>
              <td style="font-family:'Space Mono'; color:var(--text-sub)">cs_live_7716...</td>
              <td style="font-weight:700">Musa Ibrahim</td>
              <td>₦ 8,200.00</td>
              <td><span class="status-pill">Processing</span></td>
              <td style="font-family:'Space Mono'; font-size:11px">1 hour ago</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </main>


<!-- Modal: Project Configuration -->

@endsection
@push('styles')
    <style>
    .main{ 
  padding: 40px; 
  overflow-y:auto; 
  display:flex; 
  flex-direction:column; 
  gap:32px;
  width: 100%;
}

.view-header{ margin-bottom: 8px; }
.view-title{ font-size:28px; font-weight:800; }

/* Metrics Grid - Adjusted for better wrapping */
.metrics-grid {
  display: grid; 
  grid-template-columns: repeat(auto-fit, minmax(280px, 1fr)); 
  gap: 20px;
}

.stat-card {
  background: var(--bg-card); border: 1px solid var(--border);
  padding: 24px; display: flex; flex-direction: column; gap: 12px;
  min-width: 0; /* Prevents flex/grid overflow */
}
.stat-label {
  font-family: 'Space Mono', monospace; font-size: 10px;
  color: var(--text-sub); text-transform: uppercase; letter-spacing: 0.1em;
}
.stat-value { 
  font-size: clamp(24px, 2.5vw, 32px); 
  font-weight: 800; 
  white-space: nowrap; 
  overflow: hidden; 
  text-overflow: ellipsis; 
}
.stat-trend {
  font-family: 'Space Mono', monospace; font-size: 10px; color: var(--accent);
}

/* Chart Area Placeholder */
.chart-container {
  border: 1px solid var(--border); background: var(--bg-card);
  height: 300px; padding: 24px; display: flex; flex-direction: column; gap: 20px;
  min-width: 0;
}
.chart-viz {
  flex: 1; border-bottom: 1px solid var(--border-mid); border-left: 1px solid var(--border-mid);
  position: relative; display: flex; align-items: flex-end; gap: 8px; padding: 0 10px;
}
.bar {
  flex: 1; background: var(--accent-dim); border: 1px solid var(--accent);
  transition: height 0.6s ease;
}

/* Recent Activity with Table Overflow Fix */
.section-label {
  font-family: 'Space Mono', monospace; font-size: 10px;
  color: var(--text-sub); text-transform: uppercase; margin-bottom: 16px; display: block;
}

.table-responsive {
  width: 100%;
  overflow-x: auto;
  border: 1px solid var(--border);
  scrollbar-width: thin;
  scrollbar-color: var(--border-mid) transparent;
}

.activity-table {
  width: 100%; border-collapse: collapse; min-width: 700px;
}
.activity-table th {
  text-align: left; background: var(--bg-off); padding: 12px 20px;
  font-family: 'Space Mono', monospace; font-size: 10px; color: var(--text-sub);
  text-transform: uppercase; border-bottom: 1px solid var(--border);
}
.activity-table td {
  padding: 16px 20px; font-size: 13px; border-bottom: 1px solid var(--border);
  white-space: nowrap;
}
.activity-table tr:last-child td { border-bottom: none; }
.status-pill {
  font-family: 'Space Mono', monospace; font-size: 9px; text-transform: uppercase;
  padding: 2px 8px; border: 1px solid var(--border-mid);
}

/* Small Screen Adjustments */
@media (max-width: 1024px) {
  .app-shell { grid-template-columns: 80px 1fr; }
  .sidebar .nav-item { justify-content: center; padding: 20px; font-size: 0; }
  .sidebar .nav-item::before { content: ''; width: 20px; height: 20px; background: var(--text-sub); mask: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='none' stroke='black' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'%3E%3Crect x='3' y='3' width='7' height='7'/%3E%3Crect x='14' y='3' width='7' height='7'/%3E%3Crect x='14' y='14' width='7' height='7'/%3E%3Crect x='3' y='14' width='7' height='7'/%3E%3C/svg%3E") no-repeat center; }
  .main { padding: 24px; }
}
    </style>
@endpush
@push('scripts')
   <script>
  // Simple bar chart generator
  const data = [40, 70, 45, 90, 65, 80, 55];
  const chart = document.getElementById('bar-chart');

  data.forEach(val => {
    const bar = document.createElement('div');
    bar.className = 'bar';
    bar.style.height = '0%';
    chart.appendChild(bar);
    
    // Animate height
    setTimeout(() => {
      bar.style.height = val + '%';
    }, 100);
  });
</script>
@endpush